"""
core/state/session_state.py

The single shared state object that flows through the entire LangGraph pipeline.
Every agent reads from and writes to this object via the Postgres checkpointer.
"""

from __future__ import annotations
from typing import Literal, Optional
from pydantic import BaseModel, ConfigDict, Field, field_serializer
from datetime import datetime


# 
# Sub-schemas: Resume Parser output
# 

class SkillSet(BaseModel):
    technical: list[str] = Field(default_factory=list)
    tools: list[str] = Field(default_factory=list)
    soft: list[str] = Field(default_factory=list)


class WorkExperience(BaseModel):
    model_config = ConfigDict(extra="ignore")
    title: str
    company: str
    start_date: Optional[str] = None
    end_date: Optional[str] = None
    duration_months: Optional[int] = None
    role_type: Literal[
        "full_time", "internship", "other"
    ] = "full_time"
    impact_signals: list[str] = Field(default_factory=list)


class Education(BaseModel):
    model_config = ConfigDict(extra="ignore")
    degree: str
    field: Optional[str] = None
    institution: str
    year: Optional[int] = None


class CareerGap(BaseModel):
    model_config = ConfigDict(extra="ignore")
    approx_duration_months: int
    position_in_timeline: Literal["early", "mid", "recent"]


class CandidateProfile(BaseModel):
    current_title: Optional[str] = None

    years_experience_full_time: float = 0.0
    years_experience_other: float = 0.0

    seniority_level: Optional[
        Literal["intern", "junior", "mid", "senior", "lead", "principal", "executive"]
    ] = None
    skills: SkillSet = Field(default_factory=SkillSet)
    education: list[Education] = Field(default_factory=list)
    work_experience: list[WorkExperience] = Field(default_factory=list)

    # ATS summary  Claude-written narrative, primary input for ranker scoring
    ats_summary: Optional[str] = None

    career_trajectory: Optional[
        Literal["ascending", "lateral", "pivot", "re-entry"]
    ] = None
    pivot_signals: list[str] = Field(default_factory=list)
    domain_expertise: list[str] = Field(default_factory=list)
    career_gaps: list[CareerGap] = Field(default_factory=list)
    raw_text: Optional[str] = None


# 
# Sub-schemas: Profile Recommender output
# 

class SuggestedProfile(BaseModel):
    title: str
    seniority_target: Literal["junior", "mid", "senior", "lead", "principal"]
    confidence: Literal["high", "medium", "low"]
    match_reason: str
    is_stretch: bool = False
    source: Literal["system", "user_custom"] = "system"
    # Common alternative titles for this role used in job postings (abbreviations,
    # industry synonyms). Generated by the profile recommender for internal job
    # search expansion only -- never displayed in the UI.
    search_variants: list[str] = Field(default_factory=list)


# 
# Sub-schemas: Job Search output
# 

class RawJob(BaseModel):
    job_id: str
    title: str
    company: str
    location: str
    work_type: Optional[str] = None
    jd_text: str
    apply_url: str
    source: str                         # adzuna / jsearch / remoteok / firecrawl
    posted_date: Optional[datetime] = None
    matched_profile: str                # which confirmed profile triggered this


# 
# Sub-schemas: Ranker output
# 

class RankedJob(BaseModel):
    job_id: str
    title: str
    company: str
    location: str
    work_type: Optional[str] = None
    jd_text: str
    apply_url: str
    source: str
    posted_date: Optional[datetime] = None
    matched_via: list[str] = Field(default_factory=list)
    matched_profile: str = ""              # which confirmed profile this job ranked under

    # Composite score  displayed as overall fit % to the user
    fit_score: float = 0.0

    # Sub-scores  all displayed to user on job card
    experience_score: float = 0.0
    skill_score: float = 0.0
    domain_score: float = 0.0
    recency_score: float = 0.0
    education_score: Optional[float] = None   # null when JD has no education requirement
    education_required: bool = False          # true when LLM found explicit edu requirement

    # Title relevance -- how well the actual job title matches the searched profile.
    # Scored by the LLM (0.0-1.0); used as a post-score filter via
    # ranker.min_title_relevance in llm_config.yaml. Not included in fit_score.
    title_relevance: Optional[float] = None

    # Scoring notes + gap analysis from Claude (zero extra API cost  same call)
    scoring_notes: str = ""
    experience_gap: Optional[str] = None      # e.g. "Requires 5yr, candidate has 0.8yr"
    skill_gaps: list[str] = Field(default_factory=list)   # e.g. ["Kubernetes", "dbt"]
    domain_gap: Optional[str] = None          # e.g. "Role in healthcare; background pharma"
    education_gap: Optional[str] = None       # e.g. "Requires Master's; candidate has Bachelor's"

    # LLM-judged accessibility for India-based remote candidates.
    # True  = no geographic restriction, or silent (benefit of the doubt).
    # False = JD explicitly requires US work authorisation / residency / no visa sponsorship.
    # Non-remote jobs are always True (location is handled by E3 filter).
    india_accessible: bool = True

    # Sparse JD flag -- set True when the JD has fewer words than
    # ranker.sparse_jd_word_threshold. fit_score is capped at
    # ranker.sparse_jd_fit_score_cap to prevent near-empty JDs from
    # topping the leaderboard with inflated neutral scores.
    sparse_jd: bool = False


# 
# Sub-schemas: Hiring Signals output
# 

class HiringSignal(BaseModel):
    model_config = ConfigDict(extra="ignore")
    company:              str
    signal_type:          Literal[
        "funding", "expansion", "product_launch",
        "headcount_growth", "hiring_freeze", "layoff", "neutral"
    ]
    signal_strength:      Literal["high", "medium", "low"]
    summary:              str
    is_positive:          bool = True
    confidence:           float = 0.5
    source_url:           str = ""
    source_date:          Optional[datetime] = None
    source_name:          str = ""
    jobs_you_matched:     int = 0        # ties signal back to user's ranked results
    relevant_to_profiles: list[str] = Field(default_factory=list)


# 
# User preferences (Step 1 input)
# 

class UserPreferences(BaseModel):
    location: Optional[str] = None
    seniority_preference: Literal["same_level", "step_up", "open"] = "open"


# 
# Master session state  the LangGraph state object
# 

class SessionState(BaseModel):
    """
    Single source of truth for the entire pipeline.
    Persisted to Postgres via LangGraph checkpointer.
    Every agent reads from and writes to this object.
    """

    # Identity
    session_id: str
    created_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: datetime = Field(default_factory=datetime.utcnow)

    # Step 1: Raw inputs
    resume_file_name: Optional[str] = None
    resume_raw_text: Optional[str] = None
    preferences: Optional[UserPreferences] = None

    # Step 2: Parser output
    candidate_profile: Optional[CandidateProfile] = None
    parse_failed: bool = False
    parse_failure_reason: Optional[str] = None

    # Step 3: Recommender output + user confirmation
    suggested_profiles: list[SuggestedProfile] = Field(default_factory=list)
    confirmed_profiles: list[SuggestedProfile] = Field(default_factory=list)
    awaiting_confirmation: bool = False

    # Step 4: Job search output
    raw_jobs: list[RawJob] = Field(default_factory=list)

    # Step 5: Ranked output
    ranked_jobs: list[RankedJob] = Field(default_factory=list)

    # Step 6: Hiring signals
    hiring_signals: list[HiringSignal] = Field(default_factory=list)
    watch_list:     list[HiringSignal] = Field(default_factory=list)

    # Step 7: Final assembled payload ready for frontend
    results_ready: bool = False

    # Pipeline control
    current_agent: Optional[str] = None
    error: Optional[str] = None

    # Zero-results 